"""Back substitution through a lexicographic Groebner basis.

For a zero dimensional ideal, a lex basis G with x1 > x2 > ... > xn has a
triangular shape: G intersect Q[xn] is generated by one univariate
polynomial, G intersect Q[x(n-1), xn] adds polynomials in two variables,
and so on (elimination theorem). We walk from the last variable to the
first. At every level we substitute the values found so far, which leaves a
family of univariate polynomials whose common roots are exactly the
extensions of the partial solution.

Two arithmetic regimes are kept apart on purpose:

* while every value found so far is rational, substitution stays exact, we
  take the exact gcd of the family (so common roots come out of one
  polynomial with no tolerance games) and make it square free before root
  finding;
* once an irrational value is involved we switch to complex floats, pick the
  lowest degree member of the family and keep only roots at which every
  other member numerically vanishes.

Numeric roots are found with the Aberth method and polished with Newton
steps. A root is reported as an exact Fraction whenever a small denominator
rational approximation satisfies the polynomial exactly.
"""

from __future__ import annotations

import cmath
from fractions import Fraction
from typing import Dict, List, Sequence

from .ring import Poly

# ---------------------------------------------------------------------------
# dense univariate helpers; coefficient lists are low degree first
# ---------------------------------------------------------------------------


def _trim(c: list, tol: float = 0.0) -> list:
    c = list(c)
    while c and (c[-1] == 0 if tol == 0 else abs(c[-1]) <= tol):
        c.pop()
    return c


def _q_divmod(a: list, b: list):
    a = _trim(a)
    b = _trim(b)
    if not b:
        raise ZeroDivisionError
    q = [Fraction(0)] * max(len(a) - len(b) + 1, 1)
    r = list(a)
    while len(r) >= len(b) and r:
        k = len(r) - len(b)
        f = r[-1] / b[-1]
        q[k] = f
        for i, bc in enumerate(b):
            r[i + k] -= f * bc
        r = _trim(r)
    return _trim(q), r


def q_gcd(a: list, b: list) -> list:
    a, b = _trim(a), _trim(b)
    while b:
        _, r = _q_divmod(a, b)
        a, b = b, r
    if not a:
        return a
    lc = a[-1]
    return [c / lc for c in a]


def q_squarefree(a: list) -> list:
    a = _trim(a)
    if len(a) <= 2:
        return a
    da = [a[i] * i for i in range(1, len(a))]
    g = q_gcd(a, da)
    if len(g) <= 1:
        return a
    q, r = _q_divmod(a, g)
    assert not r
    return q


def horner(c: Sequence, x):
    acc = 0
    for coef in reversed(c):
        acc = acc * x + coef
    return acc


def _deriv(c: Sequence) -> list:
    return [c[i] * i for i in range(1, len(c))]


def numeric_roots(coeffs: Sequence, max_iter: int = 500) -> List[complex]:
    """All complex roots via the Aberth method (simultaneous Newton with
    repulsion). Works for complex coefficients."""
    c = [complex(x) for x in _trim(list(coeffs))]
    n = len(c) - 1
    if n < 1:
        return []
    # strip roots at zero
    zeros = 0
    while abs(c[0]) == 0 and len(c) > 1:
        c.pop(0)
        zeros += 1
    n = len(c) - 1
    roots: List[complex] = [0j] * zeros
    if n == 0:
        return roots
    if n == 1:
        return roots + [-c[0] / c[1]]
    lead = c[-1]
    mon = [x / lead for x in c]
    bound = 1 + max(abs(x) for x in mon[:-1])  # Cauchy bound
    z = [bound * 0.5 * cmath.exp(2j * cmath.pi * k / n + 0.4j) for k in range(n)]
    d = _deriv(mon)
    for _ in range(max_iter):
        moved = 0.0
        for k in range(n):
            pk = horner(mon, z[k])
            dk = horner(d, z[k])
            if dk == 0:
                z[k] += 1e-8
                continue
            ratio = pk / dk
            s = sum(1 / (z[k] - z[j]) for j in range(n) if j != k and z[k] != z[j])
            denom = 1 - ratio * s
            w = ratio / denom if denom != 0 else ratio
            z[k] -= w
            moved = max(moved, abs(w) / max(1.0, abs(z[k])))
        if moved < 1e-15:
            break
    # Newton polishing
    for k in range(n):
        for _ in range(3):
            dk = horner(d, z[k])
            if dk == 0:
                break
            z[k] -= horner(mon, z[k]) / dk
    return roots + z


def _snap(root: complex, exact_coeffs, tol: float):
    """Return an exact Fraction if one is confirmed, else a float or complex."""
    if abs(root.imag) <= tol * max(1.0, abs(root)):
        x = root.real
        if exact_coeffs is not None:
            for den in (10 ** 6, 10 ** 3):
                q = Fraction(x).limit_denominator(den)
                if horner(exact_coeffs, q) == 0:
                    return q
        return x
    return root


def _close(a, b, tol) -> bool:
    return abs(complex(a) - complex(b)) <= tol * max(1.0, abs(complex(a)))


# ---------------------------------------------------------------------------
# lex back substitution
# ---------------------------------------------------------------------------


def _specialise(g: Poly, i: int, values: Dict[int, object]) -> list:
    """Coefficients (low first) of g as a polynomial in variable i after
    substituting values for the variables after i."""
    deg = g.degree(i)
    out = [0] * (deg + 1) if deg >= 0 else []
    for m, c in g.terms.items():
        t = c
        for j, e in enumerate(m):
            if j > i and e:
                t = t * values[j] ** e
        out[m[i]] = out[m[i]] + t
    return out


def solve_lex(G: Sequence[Poly], tol: float = 1e-9, real_only: bool = False) -> List[Dict[str, object]]:
    if not G:
        raise ValueError("empty basis: every point is a solution")
    ring = G[0].ring
    n = ring.nvars
    # bucket basis elements by their smallest (lex largest) variable index
    levels: List[List[Poly]] = [[] for _ in range(n)]
    for g in G:
        used = [k for k, e in enumerate(_support(g)) if e]
        if not used:
            return []  # constant: inconsistent
        levels[min(used)].append(g)

    partial: List[Dict[int, object]] = [{}]
    for i in range(n - 1, -1, -1):
        nxt: List[Dict[int, object]] = []
        for sol in partial:
            exact = all(isinstance(v, (int, Fraction)) for v in sol.values())
            fam = [_specialise(g, i, sol) for g in levels[i]]
            if exact:
                fam = [_trim([Fraction(x) for x in f]) for f in fam]
                fam = [f for f in fam if f]
                if not fam:
                    raise ValueError("solution set is not finite at this point")
                h = fam[0]
                for f in fam[1:]:
                    h = q_gcd(h, f)
                if len(h) <= 1:
                    continue  # no common root: partial solution does not extend
                h = q_squarefree(h)
                cands = [_snap(r, h, tol * 100) for r in numeric_roots(h)]
                checks = []
            else:
                scale = max((abs(complex(x)) for f in fam for x in f), default=1.0) or 1.0
                fam = [_trim([complex(x) for x in f], tol * scale) for f in fam]
                fam = [f for f in fam if len(f) > 0]
                nonconst = [f for f in fam if len(f) > 1]
                if any(len(f) == 1 for f in fam):
                    continue  # a non-zero constant survived: no extension
                if not nonconst:
                    raise ValueError("solution set is not finite at this point")
                nonconst.sort(key=len)
                h = nonconst[0]
                cands = [_snap(r, None, tol * 100) for r in numeric_roots(h)]
                checks = nonconst[1:]
            seen: List[object] = []
            for r in cands:
                if any(_close(r, s, 1e-7) for s in seen):
                    continue
                ok = True
                for f in checks:
                    sc = max(abs(x) for x in f)
                    if abs(horner(f, complex(r))) > 1e-6 * sc * max(1.0, abs(complex(r))) ** (len(f) - 1):
                        ok = False
                        break
                if ok:
                    seen.append(r)
                    s2 = dict(sol)
                    s2[i] = r
                    nxt.append(s2)
        partial = nxt

    out = []
    for sol in partial:
        d = {ring.variables[k]: sol[k] for k in range(n)}
        if real_only and any(isinstance(v, complex) for v in d.values()):
            continue
        out.append(d)
    out.sort(key=lambda d: tuple(_sort_key(d[v]) for v in ring.variables))
    return out


def _support(g: Poly):
    used = [0] * g.ring.nvars
    for m in g.terms:
        for k, e in enumerate(m):
            if e:
                used[k] = 1
    return used


def _sort_key(v):
    c = complex(v)
    return (abs(c.imag) > 1e-12, c.real, c.imag)
